### PR TITLE
validate schema makefile

### PR DESCRIPTION
**Pull request by claudiol**
- Adding validate-schema target
- Added entry to Changes.md for validate-schema Makefile target

### CODE REVIEW

**Comment by mbaldessari** [comment]
The reason I am not super fond of adding this is that the helm options that we pass here, are not the ones that argo will pass down. Those have a bunch of additional values-* files whereas here we only have values-global.yaml file. So this would be a very rough approximation. If we were to add this here properly we would have to readd a lot of logic with all the right values files to make it useful?

**Comment by mbaldessari** [comment]
We could do something like:
```
diff --git a/common/Makefile b/common/Makefile
index d95b889..760072c 100644
--- a/common/Makefile
+++ b/common/Makefile
@@ -35,8 +35,13 @@ validate-origin: ## verify the git origin is available
                echo "Running inside a container: Skipping git ssh checks";\
        fi

+.PHONE: validate-schema
+validate-schema: ## validates values files against schema in common/clustergroup
+       $(eval VAL_PARAMS := $(shell for i in ./values-*.yaml; do echo -n "-f $${i} "; done))
+       helm template common/clustergroup --name-template $(NAME) $(HELM_PARAMS) $(VAL_PARAMS) >/dev/null
+
 .PHONY: operator-deploy operator-upgrade
-operator-deploy operator-upgrade: validate-origin ## runs helm install
+operator-deploy operator-upgrade: validate-origin validate-schema ## runs helm install
        helm upgrade --install $(NAME) common/operator-install/ $(HELM_OPTS)

 .PHONY: deploy upgrade legacy-deploy legacy-upgrade
```

But if we do this, I think we should first investigate and fix these warnings as they'd scare people off:
```
helm template common/clustergroup --name-template multicloud-gitops  -f ./values-global.yaml -f ./values-group-one.yaml -f ./values-group-two.yaml -f ./values-hub.yaml  >/dev/null
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/michele/Engineering/Labs/hub-region-aws/region/auth/kubeconfig
coalesce.go:223: warning: destination for pattern-clustergroup.clusterGroup.applications is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for pattern-clustergroup.clusterGroup.managedClusterGroups is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for pattern-clustergroup.clusterGroup.subscriptions is a table. Ignoring non-table value ([])
make[1]: Leaving directory '/home/michele/Engineering/cloud-patterns/multicloud-gitops'
```

**Comment by mbaldessari** [comment]
Warning fixes are here https://github.com/hybrid-cloud-patterns/common/pull/251

**Comment by claudiol** [comment]
Closing since PR #252 supersedes the changes here.

**Pull request closed without merging**
