### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by mbaldessari**
- Split off global helm variables to a helper definition
- Fix up spacing
- Switch ApplicationSets to use the newly-introduced helpers
- Split off valueFiles to _helpers.tbl
- Fix up spacing
- Switch applicationsets to use the new helper
- Drop some older comments

### CODE REVIEW

**Comment by mbaldessari** [comment]
Tested this with MCG and everything worked

**Review by mhjacks — APPROVED** [review]
LGTM

**Comment by day0hero** [comment]
LGTM

**Comment by mbaldessari** [comment]
Thanks guys! I just did a small tweak where the definition uses {{- define "foo" -}} and then I use nindent in the include. This avoids the spurious spaces on the line preceding the include and makes this PR quite smaller

**Pull request merged**
