### PR TITLE
Added callbacks to ansible.cfg

### PR DESCRIPTION
**Pull request by day0hero**
The profile_roles and profile_tasks callbacks provide timinng
information for tasks and roles to execute.

### CODE REVIEW

**Comment by day0hero** [comment]
Task run w/out callback:
```
TASK [vault_utils : Check if ~/.kube/config exists] **********************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [vault_utils : Check if we're running inside an OCP cluster directly] ***********************************************************************************************************************************************************************************
ok: [localhost]

```

Task run with callback:
```
TASK [vault_utils : Check if ~/.kube/config exists] **********************************************************************************************************************************************************************************************************
ok: [localhost]
Thursday 06 October 2022  12:35:39 -0500 (0:00:00.328)       0:00:01.206 ****** 
Thursday 06 October 2022  12:35:39 -0500 (0:00:00.328)       0:00:01.205 ****** 

TASK [vault_utils : Check if we're running inside an OCP cluster directly] ***********************************************************************************************************************************************************************************
ok: [localhost]
Thursday 06 October 2022  12:35:39 -0500 (0:00:00.078)       0:00:01.285 ****** 
Thursday 06 October 2022  12:35:39 -0500 (0:00:00.078)       0:00:01.283 ****** 
```

**Comment by mbaldessari** [comment]
What is ansible's behavior if 'callback_whitelist = profile_roles, profile_tasks' one of these callback plugins is missing on the system? (For whatever reason, odd OS, ansible version, etc). Does it still work or does it barf?

**Comment by claudiol** [comment]
@mbaldessari It looks like if it can't find the white listed callbacks it throws a warning.
$ ansible-playbook ./load-secrets.yaml 
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callbacks_enabled instead. This feature will be removed from ansible-core in version 2.15. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: Skipping callback plugin 'profile_myroles', unable to load
[WARNING]: Skipping callback plugin 'profile_mytasks', unable to load

The version I used is ansible-playbook [core 2.12.9].

**Comment by mbaldessari** [comment]
So we should probably at the very least use callbacks_enabled instead?

**Comment by day0hero** [comment]
@mbaldessari:
with `callbacks_enabled=profile_roles,profile_tasks` enabled 

and the following collections removed (`~/.ansible/collections/ansible_collections/`)
- ansible.posix
- community.crypto
- community.general

I was able to run `make load-secrets` and get the feedback from the callback:

```
Monday 17 October 2022  16:55:54 -0500 (0:00:01.992)       0:00:11.027 ********
===============================================================================
vault_utils ------------------------------------------------------------ 11.00s
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
total ------------------------------------------------------------------ 11.00s
Monday 17 October 2022  16:55:54 -0500 (0:00:01.992)       0:00:11.026 ********
===============================================================================
vault_utils : Loads secrets file into the vault of a cluster --------------------------------------------------------------------------------------------------------------- 1.99s
vault_utils : Check for the vault status ----------------------------------------------------------------------------------------------------------------------------------- 1.69s
vault_utils : If the vault is still sealed we need to retry ---------------------------------------------------------------------------------------------------------------- 1.36s
vault_utils : Make sure that the vault auth policy exists ------------------------------------------------------------------------------------------------------------------ 1.31s
vault_utils : Check for vault namespace ------------------------------------------------------------------------------------------------------------------------------------ 1.14s
vault_utils : Check if the vault pod is present ---------------------------------------------------------------------------------------------------------------------------- 1.06s
vault_utils : List Vault pods ---------------------------------------------------------------------------------------------------------------------------------------------- 0.99s
vault_utils : Check if the kubernetes python module is usable from ansible ------------------------------------------------------------------------------------------------- 0.80s
vault_utils : Check if ~/.kube/config exists ------------------------------------------------------------------------------------------------------------------------------- 0.34s
vault_utils : Get pods ----------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
vault_utils : Check if KUBECONFIG is correctly set ------------------------------------------------------------------------------------------------------------------------- 0.04s
vault_utils : Set vault status output json fact ---------------------------------------------------------------------------------------------------------------------------- 0.04s
vault_utils : Check if we're running inside an OCP cluster directly -------------------------------------------------------------------------------------------------------- 0.04s
vault_utils : Followers ---------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
vault_utils : Fail if both KUBECONFIG and ~/.kube/config do not exist but only when not running in a cluster --------------------------------------------------------------- 0.03s
vault_utils : include_tasks ------------------------------------------------------------------------------------------------------------------------------------------------ 0.03s
vault_utils : include_tasks ------------------------------------------------------------------------------------------------------------------------------------------------ 0.03s
vault_utils : Set secret_template fact ------------------------------------------------------------------------------------------------------------------------------------- 0.03s
```

So from what I can tell, the callbacks will continue to work even without core collections.

**Comment by mbaldessari** [comment]
@day0hero can you use the non deprecated name: `callbacks_enabled`?

**Comment by day0hero** [comment]
@mbaldessari - I updated with the appropriate parameter.

**Comment by mbaldessari** [comment]
I am fine merging this. Want to remove the draft and merge it?

**Pull request merged**
