### PR TITLE
Add 'make test' to every common/ PR

### PR DESCRIPTION
**Pull request by mbaldessari**
- Fix test error in clustergroup example
- Fix acm naked example test
- Fix tests/clustergroup-normal.expected.yaml test
- Add initial checking github action on every pull/push

### CODE REVIEW

**Comment by mbaldessari** [comment]
Mmh not sure why the CI run is only being shown on my branch and not here. I need to figure that part out

**Comment by beekhof** [comment]
Nice :)

**Comment by beekhof** [comment]
Maybe the CI bits need to be merged first

**Comment by mbaldessari** [comment]
I think so, I'll just go ahead and merge this. It's just informational for now, so should not be a big deal.

**Comment by mbaldessari** [comment]
Yep that was it

**Pull request merged**
