### PR TITLE
managed cluster group fix

### PR DESCRIPTION
**Pull request by claudiol**
- - Change to generate the RHACM PlacementRule with the correct label described in values-hub.yaml

### CODE REVIEW

**Comment by claudiol** [comment]
@mbaldessari 
Summary: The RHACM PlacementPolicy generated for selecting clusters was using the name of the managedClusterGroup and not the label in values-hub.yaml

Details:
In values-hub.yaml we have the following definition for a **managedClusterGroup**:
```
  managedClusterGroups:
    exampleRegion:
      name: group-one
      labels:
      - name: clusterGroup
        value: group-one
      helmOverrides:
      - name: clusterGroup.isHubCluster
        value: false
```
The reason this appears to work is because we define the name of the clustergroup as *group-one* and the label as *group-one* as well. I say it appears to work because if I change the label to *foo-group* what is being generated by the ACM chart is the following:
```
# Source: acm/templates/policies/application-policies.yaml
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: group-one-placement
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      clusterGroup: group-one
```
Notice that the **matchLabels:** value is not correct. It should be *foo-one*.  The change in applications-policies.yaml will render the correct PlacementRule and will also handle the list of labels correctly.

Let me know if you want to chat about this change.

**Comment by mbaldessari** [comment]
Shouldn't we just change the values-hub.yaml to use acmlabesl:? Otherwise we're making acmlabels and labels the exact same thing and that just feels wrong?

**Comment by claudiol** [comment]
Ok I will test with acmlabels and see. But are we going to support a list of labels? As it stands right now we do not support the list of labels. So either we say it's a list of **acmlabels**, and remove the support of list of **labels**, or we say we support both list of **labels**, and **acmlabels**.

**Comment by beekhof** [comment]
> Shouldn't we just change the values-hub.yaml to use acmlabesl:? Otherwise we're making acmlabels and labels the exact same thing and that just feels wrong?

IIRC, we invented labels and then very soon after added support for hosted Argo... at which point I s/labels/acmlabels/ to avoid people thinking it was relevant to Argo.  I was under the impression patterns weren't using labels when I made that change 

+1 to change the values-hub.yaml

**Comment by mbaldessari** [comment]
> > Shouldn't we just change the values-hub.yaml to use acmlabesl:? Otherwise we're making acmlabels and labels the exact same thing and that just feels wrong?
> 
> IIRC, we invented labels and then very soon after added support for hosted Argo... at which point I s/labels/acmlabels/ to avoid people thinking it was relevant to Argo. I was under the impression patterns weren't using labels when I made that change
> 
> +1 to change the values-hub.yaml

Ack, that is what we ended up doing. Closing this one

**Pull request closed without merging**
